name = "LeanRAG"
version = "0.1.0"
defaultTargets = ["leanrag"]

[[lean_lib]]
name = "LeanRAG"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "c104265c34eb8181af14e8dbc14c2f034292cb02"

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "d835296a6149acb9bd2ff65ec01b728b9cc99a1c"

[[lean_exe]]
name = "leanrag"
root = "Main"

[[lean_exe]]
name = "extract_declarations_info"
root = "LeanRAG.ExtractDeclarationsInfo"
supportInterpreter = true

[[lean_exe]]
name = "get_initial_proofstate"
root = "LeanRAG.GetInitialProofstate"
supportInterpreter = true