name = "LeanRAG"
version = "0.1.0"
defaultTargets = ["leanrag"]

[[lean_lib]]
name = "LeanRAG"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "b2e8b6868397fcd93c00aca7278b933c16c0ffb3"

[[require]]
name = "Cli"
git = "https://github.com/taterowney/lean4-cli"
rev = "3e2b220813ebeb2b81930eb6a6a6524ef5d2ca98"

[[lean_exe]]
name = "leanrag"
root = "Main"

[[lean_exe]]
name = "extract_declarations_info"
root = "LeanRAG.ExtractDeclarationsInfo"
supportInterpreter = true

[[lean_exe]]
name = "get_initial_proofstate"
root = "LeanRAG.GetInitialProofstate"
supportInterpreter = true