name = "LeanRAG"
version = "0.1.0"
defaultTargets = ["leanrag"]

[[lean_lib]]
name = "LeanRAG"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "7a0d63fbf8fd350e891868a06d9927efa545ac1e"

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "f9e25dcbed001489c53bceeb1f1d50bbaf7451d4"

[[lean_exe]]
name = "leanrag"
root = "Main"

[[lean_exe]]
name = "extract_states"
root = "LeanRAG.ExtractStates"
